### ISSUE TITLE
Agregar menú para configuraciones

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#1]
Que haya un botón de menú, que al tocar despligue un modal que pida PIN de 4 dígitos para acceder  a las siguientes opciones:

-Enrolar
-Registrar
-Configuración
-Información del Equipo

Si no se ingresa un PIN en los 5 segundos, que se cierre el modal automáticamente.

Además borrar las tabs.

Para entender como funcionan los menús http://ionicframework.com/docs/api/directive/ionSideMenus/

También se puede crear una app desde cero en una nueva carpeta haciendo  ionic start myApp sidemenu

**Comment by AlexisNichel** [comment]
Listo, faltaría observar bien si los tiempos son justos, ademas ya esta la validación para que el click abra el modal solo si el side esta cerrado. por el momento cierro este issue y continuo
