### ISSUE TITLE
Reloj en el header

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#10]
Agregar la hora con dos dígitos en la esquina superior derecha del header. Ej: 8:25

Debería mostrarse con un tamaño de font-size lo suficientemente visible

Con asignar `$scope.clock = new Date()` debería alcanzar. Luego en el html será necesario parsearlo para que lo muestre con dos dígitos.

**Comment by AlexisNichel** [comment]
No lo cierro aun por que no se como meter el reloj en la barra de arriba

**Comment by AlexisNichel** [comment]
Listo
