### ISSUE TITLE
Corregir timeout en la página de verificación

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#12]
Que al hacer click en alguna parte del modal de login no lo cancele, sino que haga un reset.

**Comment by AlexisNichel** [comment]
listo con click y a cada letra ingresada o borrada del form resetea el temporizador

**Comment by AlexisNichel** [comment]
vuelvo a abrir por que encontre un bug medio extraño despues de probar el form 5 o 6 veces empieza a hacer otra cosa, lei que puede ser por la cache pero no se aun que es

**Comment by AlexisNichel** [comment]
ahora si, el resto de lo que falta en el login lo voy viendo con el otro issue que pide lo del menu inicial nada mas y eso
