### ISSUE TITLE
No recibir respuestas por textos, sino por códigos HTTP

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#13]
en www/js/controllers:

![image](https://cloud.githubusercontent.com/assets/1928706/13901973/e42385a6-ee14-11e5-8d03-b65b4871fb07.png)

Preguntar por status code, 200, 500 etc. ya que los strings pueden cambiar.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by AlexisNichel** [comment]
cambiado a codigos, en el otro issue al maejar los errores continuare comparando codigos.
