### ISSUE TITLE
Errores en formularios y envíos al servidor

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#14]
Para formularios antes de hacer submit, utilizar este como ejemplo:
http://plnkr.co/edit/5iyyVImCF8EEesN1jNfy?p=preview

Una vez enviada la respuesta al servidor, se pueden mostrar los mensajes con:

``` javascript
$ionicLoading.show({ template: 'Error|Todo ok!', duration: 2000 });
```

En algunos lugares hay un timeout para esto, como en enroll.js. Quitarlo

**Comment by camposcristianeze** [comment]
Hay muchos archivos que en el .then no tienen el error directamente. Hacer `cntrl+shift+f` para buscar todos los .then y fijarse que muestren el mensaje de error.

**Comment by AlexisNichel** [comment]
$ionicLoading.show({ template: 'Error|Todo ok!', duration: 2000 }); esto ya esta

**Comment by AlexisNichel** [comment]
agregados los .then error

**Comment by AlexisNichel** [comment]
los views cambiare por el log donde sea necesario cuando llegue a ese commit

**Comment by camposcristianeze** [comment]
Estuve revisando el código y hay varias cosas a corregir para poder utilizarlo.

El link `http://plnkr.co/edit/5iyyVImCF8EEesN1jNfy?p=preview`de plunker, en la esquina superior izquierda tiene una pestaña con "files". Las clases css no son tan necesarias (Aunque se pueden reutilizar").  Lo más importante son las directivas que van dentro de directive y el form en el html que debería quedar de esta manera:

![image](https://cloud.githubusercontent.com/assets/1928706/14066012/73dd85f6-f415-11e5-81ac-5256fe879318.png)

No es necesario abrir un nuevo styleform.css. Sino directo en el styles.css. Separarlo por un comentario Que diga "//----- Form Styles ------"

Falta inicializar mustEnroll. Al ser required debe tener si o si un valor para que el formulario sea válido.

**Comment by AlexisNichel** [comment]
ya valida no se si de la forma correcta
