### ISSUE TITLE
Evitar utilizar nombres técnicos para definir comportamientos y expresiones booleanas redundantes 

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#15]
![image](https://cloud.githubusercontent.com/assets/1928706/13902022/aba2eec2-ee16-11e5-866f-4600484cb85a.png)

En vez de utilizar la palabra toggle que es algo técnico del framework específicamente, utilizar un nombre como "debeEnrolar" en inglés "mustEnrol"
Además, if (mustEnrol == true) seria redundante ya que las variables que representan booleanos no hace falta compararlas,  ya que el resultado es true o false. En este caso iría directamente:

``` js
if(mustEnroll)
```
Mismo caso en flag menu.js,  reemplazarlo por isOpened  o isClosed, por ejemplo.
![image](https://cloud.githubusercontent.com/assets/1928706/13902057/970463aa-ee17-11e5-8ef2-2b24216d24f2.png)

De esta manera aportamos mayor declaratividad al código.

De yapa, agregar todos los puntos y comas faltantes en register.js

**Comment by AlexisNichel** [comment]
listo cambiado flags y toogle, de paso verificare los ; en todos los js
