### ISSUE TITLE
Utilizar un archivo para todos los logs.

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#16]
Utilizar la siguiente librería (ya está instalada) para guardar todos los logs en el teléfono y luego poder enviarlos en caso de errores.

https://github.com/pbakondy/filelogger

**Comment by AlexisNichel** [comment]
ya agregue pero no se como probar si esta generando el archivo

**Comment by camposcristianeze** [comment]
Se podría verificar donde se está guardando con

$*fileLogger.checkFile**()*

**Comment by AlexisNichel** [comment]
no me funciono de esa forma pero ya verifique con esto  $fileLogger.checkFile().then(function(d) {
        console.log('Logfile data');
        console.log(JSON.stringify(d));
      });

**Comment by AlexisNichel** [comment]
lo que faltaria es ver en que partes esta bien, y en que parte no es necesario solo le puse a los errores

**Comment by camposcristianeze** [comment]
Ok, nos juntamos y lo evaluamos entre los 3 con Reinaldo
