### ISSUE TITLE
Pantalla para editar usuarios

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#19]
Pantalla con la misma interfaz gráfica de Enrolar. Pensar/Investigar la manera de respetar la práctica  DRY (Don't Repeat Yourself) y no copiar y pegar código, sino utilizar la misma pantallas dos pantallas que ya están generar la nueva funcionalidad.

### Algunas ideas:

- Si o si se deberá crear una nueva ruta en routes.js. Pero se podría llamar al mismo controller y el mismo html de enrolar, nada más cambiando la ruta de la url a /modify.
- Lo único que cambiaría del html sería el ng-click, que llamaría a la pantalla de registrar en vez de hacer el enrolamiento. Ver como definir el ng-click desde enroll.js. Si se recibe el parámetro que se haga una cosa en el ng-click, sino la otra.
- De la misma manera se podría reutilizar register.js, si se recibe un formulario que se complete con esos datos.

**Comment by camposcristianeze** [comment]
Esta bien como lo resolviste, el problema es que las funciones deberían hacer una sola cosa y no encapsular comportamientos completamente diferentes. Por el momento dejemoslo así, fijate nada más de encapsular el comportamiento de enrolar en una función que se llame enroll y la del ng-click ponerle un nombre que englobe a ambas cosas por el momento, tanto enrolar como redirigir. Podría ser algo así como **decideAction**

**Comment by AlexisNichel** [comment]
separe las funciones y el ng/click le dice a cual ir, no me costo nada hacer asi que lo hice no mas ya
