### ISSUE TITLE
Enrolar Huella con Bioid

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#2]
Al hacer click en el botón enrolar, levantar un $ionicloading que vaya indicando el estado del sensor (Ingrese dedo una vez, dos veces, etc). Una vez terminado el proceso, obtener la huella del sensor.

Luego de obtenerla, hacer un POST a /Enrolar con la huella. El nombre de esta función que hace el post debe ser enroll y debe estar dentro de $api. 
Verificar que se cargue la huella en bioid.

http://apibioidcrear.azurewebsites.net/Help/Api/POST-Usuario-Enrolar

**Comment by AlexisNichel** [comment]
ok, probar mas detenidamente pero funciona
