### ISSUE TITLE
Pantalla de Configuración

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#22]
Utilizando el servicio del #17 crear una pantalla de configuración que permita editar los campos del archivo config.json. 

A la pantalla de configuración del sensor renombrarla a Configuración del Sensor

La primera vez si no existe localstorage(#21) se debe pedir los datos de config.json y mostrarlos en pantalla.  Luego al salir del menú se deben guardar en localStorage y de ahí en adelante, si existe el localstorage traerlos desde ahí directamente.

Además, agregarle los siguientes campos a config.json:

``` json
"adminPassword": "pass",
"adminUser": "user",
"idCompany":"company"
```

### Controles en cada campo, nombre y control en cada caso

- DebugMode: Modo Debug, Toggle
- retryNumber: Número de Reintentos: Select Menu con Opciones 1, 3, 5, 10
- syncInterval: Intervalo de Sincronización: Select Menu con Opciones 1 minuto(No recomendado) 5 minutos, 10 minutos, 30 minutos, 1 hora, 3 horas, 12 horas.
- waitInterval: Tiempo de espera, Select Menu con Opciones: 5 segundos, 10 segundos, 30 segundos, 1 minuto.
- menuTimeout: Tiempo Cierre Menu: Select Menu con Opciones: 5 segundos, 10 segundos, 30 segundos, 1 minuto.
adminUser,password: Usuario Admin, Contraseña Admin

**Comment by AlexisNichel** [comment]
le falta diseño pero ya esta funcional
