### ISSUE TITLE
Obtener Usuarios

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#23]
Crear un método syncUsers en un service sync.js con dependencia de api.js. Lo que va a hacer es primero obtener las huellas de localstorage sino crear un array vacío. Luego guardar las huellas por un lado para que se consulten más rápido con el lector y los datos del usuario por otro. 

 ``` js
//$api.getUsers().then(function(apiUsers){
var users = apiUsers;
var fingerPrints = $localstorage.getObject('fingerPrints ') || [], 
userData = $localstorage.getObject('users') || []
angular.forEach(usuarios, function(value) {
fingerPrints[value.IdHuella] = value.Huella;
delete value.Huella;
userData[value.IdHuella] = value;
})
$localstorage.setObject('fingerprints ',fingerprints );
$localstorage.setObject('users', userData );
$localstorage.setObject('lastSync', new Date());
//Llamar a splashScreen para escribir huellas con writeTemplate
})
```

Además, si la sincronización fue errónea dejarlo asentado en el log.

**Comment by AlexisNichel** [comment]
ok, lo hace al iniciar el programa por primera vez, trae todo de bioid y separa huellas de datos, faltaran los siguientes casos de sync
