### ISSUE TITLE
Probar en Pipo X8

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#24]
Es una prueba para probar que funcione, pero probablemente luego te sería más fácil para probarlo ya que podrías conectar el sensor directamente, entre otros.

Para debuggear en wifi
http://stackoverflow.com/questions/4893953/run-install-debug-android-applications-over-wi-fi

En ethernet (Más rápido)
http://forum.xda-developers.com/xposed/xposed-pipo-x8-infinite-bootloop-t3271400/page2

**Comment by AlexisNichel** [comment]
funciona por wifi, aun no probe por eternet y no me estira probar por ahora xq puedo causar bootloop y la imagen del pipo pesa casi 4 Gb
