### ISSUE TITLE
Cambios en pantalla de Configuración

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#28]
Agregar una línea que muestre a la izquierda la última fecha de Sincronización y a la derecha los botones de 
- Sincronizar Usuarios y Registros
- Grabar Huellas

Las llamadas a la función de los mismos estarán en sus respectivas issues.

Además, dentro del select intervalo de sincronización, agregar la opción "Al instante"

También, crear un nuevo campo url del sistema que permita consultar otras apis. Que venga preseteada con http://apibioidcrear.azurewebsites.net.

**Comment by AlexisNichel** [comment]
ya esta el html modificado, faltarian las funciones de cada una que lo hare en sus respectivos Isues
