### ISSUE TITLE
Pantalla Registrar

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#3]
Debe tener los campos necesarios para hacer una registración. Que haya un toggle que te permita mostrar u ocultar los campos opcionales: ![image](https://cloud.githubusercontent.com/assets/1928706/13650666/83b1e400-e622-11e5-9df2-49f16665afe3.png).

Luego hacer POST a /enrolar http://apibioidcrear.azurewebsites.net/Help/Api/POST-Usuario-Enrolar

Creando un nuevo método en el servicio $api que se llame register.

**Comment by AlexisNichel** [comment]
ya esta el metodo en el servicio, muestra y oculta campos(lo hice con check por que el toogle lo lleva a la derecha no se por que), hace post y espera confirmacion "OK"
Falta: salir de la pantalla de espera si responde con error 500, y cargar el objeto con datos nulos para que el bioid no pase error

**Comment by AlexisNichel** [comment]
Lo que pide este issue esta completo, luego falta control de errores y mensajes, cosas que voy haciendo en paralelo, por lo tanto lo cierro ya que en forma general esta listo
