### ISSUE TITLE
Sincronizar Registros

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#30]
En pantalla de verificar, luego de cada verificación exitosa con el lector, guardar el registro en localStorage con key **records**.  Luego, el botón de sincronizar registros en la pantalla de Configuración debe llamar a la funcion del servicio para sincronizar con bioid tomando estos registros.

**Comment by AlexisNichel** [comment]
parte 1 listo

**Comment by AlexisNichel** [comment]
falta el boton

**Comment by AlexisNichel** [comment]
ok, compara con lastsync y envia los nuevos
