### ISSUE TITLE
Sincronizar Enrolamientos, Modificaciones y Nuevos Usuarios

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#31]
Cada vez que se realizan alguna de estas 3 acciones, guardar el usuario nuevo o modificado en en localStorage con la key usersToSync.

Crear método saveUsers dentro del servicio sync.js que tome usersToSync y en un for por cada registro se llame al método postUsers de api.js.

Luego, al presionar el botón de Sincronizar Usuarios en pantalla de configuración que por un lado guarde los registros y que por otro traiga todos los cambios efectuados.

**Comment by AlexisNichel** [comment]
parte 1 ok

**Comment by AlexisNichel** [comment]
parte 2 ok metodo creado, la duda aca es si le debo de pasar fecha o algo por que si solo hago post me agregara nuevos en vez de actualizarlos

**Comment by AlexisNichel** [comment]
parte 2 ok separados post de put, esto falta probar bien, aun no probe detenidamente

**Comment by AlexisNichel** [comment]
put y pos ok, pero put lo hace por c.i ver para cambiar esto

**Comment by AlexisNichel** [comment]
listo lo de alzar por idUsuario

**Comment by AlexisNichel** [comment]
listo, probe con una sola huella y no en todos los casos de uso, falta probar detenidamente con huella, sin huella, nuevo en bioid, nuevo en equipo, etc
