### ISSUE TITLE
$api.getUsers que controle fecha

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#34]
Si se envía la fecha como parámetro, que se la llamada http.get la incluya. Sino que haga la que viene haciendo normalmente.

La fecha y hora está en un formato extraño. MES/DIA/AÑO

Ejemplo:
http://apibioidcrear.azurewebsites.net/Usuario/GetUsuarios?idEmpresa=1&fechaHora=08/23/2015

**Comment by AlexisNichel** [comment]
el api ya esta, faltaria que en el otro issue de sync le pase los parametros
