### ISSUE TITLE
deshabilitar botones de sync del menu 

### ISSUE THREAD

**Issue by AlexisNichel** [AlexisNichel/bioid-mobile-base#37]
botones de sync borrar o deshabilitar por que aun no tiene id empresa

**Comment by camposcristianeze** [comment]
Esto es cuando no tiene el id empresa seteado? o en que momento?

**Comment by AlexisNichel** [comment]
si asi mismo en config inicial

**Comment by AlexisNichel** [comment]
esto lo cierro por que lo resolvere con el issue de menu de super usuario
