### ISSUE TITLE
verificar time out sigue mal

### ISSUE THREAD

**Issue by AlexisNichel** [AlexisNichel/bioid-mobile-base#38]
solucionar time out sigue con problemas

**Comment by AlexisNichel** [comment]
listo ahora si funciona bien, quisas faltaria hacer un recorrido y ver donde resetear, por ahora lo resetea cualquier click o cambio, lo que faltaria es por ejemplo que cuando termine de enrolar y cosas asi vuelva a resetear, hare un nuevo issue para el final con eso

**Comment by camposcristianeze** [comment]
Ok! Perfecto, que era lo que estaba faltando?

**Comment by AlexisNichel** [comment]
primero que nada estaba llamando a ng-click='resetTemp' en lugar de ng-click='resetTemp()' en algunos lugares, pero esto no soluciono y era porque:
Dentro de $scope.resetTemp() habia 2 funciones una era stopTemp() y la otra reinicTemp() que estaban en el servicio correspondiente, pasa que al ser 2 funciones independiente llamaba a los 2 al mismo tiempo.

lo que hice fue en una sola  funcion poner la linea para detener y luego reiniciar, por lo tanto si o si hace una cosa y luego la otra, ahora hasta donde probe funciona bien, estos dias me dare cuenta de que tan optimo quedo.
