### ISSUE TITLE
Grilla de botones para verificar

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#4]
Utilizando `http://ionicframework.com/docs/components/#grid` , generar botones, por el momento los típicos de ionic, para la vista de verificación en la pantalla principal.  Generarlo a partir de un vector de javascript y con un ngfor del siguiente formato:

`var marks = [{name: Entrada, color: #FF0000, id:1}, {name: Salida, color: #0000ff, id:2}] `

**Comment by AlexisNichel** [comment]
Este issue lo cierro por que al pasarle un objeto creo que esto de la grilla no va, por el momento solo lo liste y continuo con la parte de verificación y demas
