### ISSUE TITLE
realizar conexion automatica

### ISSUE THREAD

**Issue by AlexisNichel** [AlexisNichel/bioid-mobile-base#42]
hacer botones de reintentar y de reconfigurar en caso de que no conecte

**Comment by AlexisNichel** [comment]
ya conecta automaticamente, falta manejar el error con los botones

**Comment by AlexisNichel** [comment]
ok, omiti lo de reconfigurar por que en realidad si al usuario no le conecta por bluetooth o lo que fuere solo deberia poder reintentar y no cambiar nada, cualquier cosa lo modifico

**Comment by camposcristianeze** [comment]
Me parece que está ok.  No es necesario que sea reconfigurable pero si que
tenga un botón de cerrar para que no quede atascado en ese menu

**Comment by AlexisNichel** [comment]
listo le puse un boton pero esta en la barra de arriba, no se si justifica que el usuario lo vea pues, es decir el equipo se debe conectar si o si pero en caso de que se necesite salir tiene en la barra el close, no se si esta bien
