### ISSUE TITLE
tamaño de los botones

### ISSUE THREAD

**Issue by AlexisNichel** [AlexisNichel/bioid-mobile-base#48]
Los botones no entran todo en el Lg, lo mire para poder hacer la demo y no entran todos en la pantalla

**Comment by camposcristianeze** [comment]
Cambié esta pantalla para que pueda ser utilizada mejor de costado. Faltaría ajustar los botones para que entren perfectamente en el font-size bioid-button-bg y bioid-button-sm. Los tamaños en pixeles deben ser simétricos (Reducirse en el mismo ratio). También se debe reducir el font-size de .text-inside
