### ISSUE TITLE
Pasada por la aplicación traduciendo a inglés textos en castellano del código

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#5]
No es necesario en los comentarios, los console.log y los textos que se muestran. Solo en el nombre de las funciones, variables, etc.

Como una parte será de código abierto, conviene que esté en inglés para poder recibir feedback.

![image](https://cloud.githubusercontent.com/assets/1928706/13747531/756937b4-e9d7-11e5-8c65-621c6edaf125.png)

![image](https://cloud.githubusercontent.com/assets/1928706/13747540/82efa86e-e9d7-11e5-9da1-529e94774fc6.png)

Como bonus, no es necesario declarar $scope.datos

**Comment by AlexisNichel** [comment]
Listo, si hay palabras en español son las palabras que no se si la traduccion de google me pasa las correctas, pero creo que estan todas
