### ISSUE TITLE
No hacer ifs por textos de respuesta del sensor

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#54]
Por ejemplo, línea 61 de verify.js

if (notificacion !== "Dejar de pulsar el sensor.") { 

Se debe filtrar por valor, no por el mensaje, En este caso es 0xf4, buscarlo en el objeto que se recibe. ya que si cambian los mensajes luego se debe cambiar cada ocurrencia en el código, idem si se debe traducir la aplicación.

**Comment by AlexisNichel** [comment]
no puedo hacerlo por que sensor js me responde con texto
