### ISSUE TITLE
Contraseña de Administrador

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#56]
En config.json, crear nuevos campo superAdminPassword y superAdminUser. Luego, comparar en el login también por estos campos y si están ok loguear como superadmin.  

El superadmin tendrá la capacidad de editar todas las configuraciones avanzadas y ver el menú de configuración del sensor, entre otras. 

Para comprobar que es superAdmin, debe agregarse al localstorage un key isSuperAdmin o al rootScope, que también puede accederse desde cualquier página. No olvidarse de borrarlo al momento de entrar en la pantalla de verificar o cuando se acaba el timeout.

**Comment by AlexisNichel** [comment]
ya esta el menu, falta ordenar los elementos dentros
