### ISSUE TITLE
Ocultar Status bar en Android

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#61]
Quitar el hidestatus bar del código. Probar con esto en el archivo config.xml en la parte de preferences:
```
<preference name="Fullscreen" value="true" />
```

**Comment by AlexisNichel** [comment]
Con esto la oculta pero permite accederla, esto no deberia pasar

**Comment by AlexisNichel** [comment]
lo bloquearemos por s.o
