### ISSUE TITLE
Posibilidad de subir logs a internet

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#65]
Se debe crear una un endpoint con un método POST /upload (Probarlo con advanced rest client) permita subir archivos desde la aplicación de ionic y luego descargarlos desde la página de azure: 

```
https://azurestorage.azurewebsites.net/Default.aspx
Account: bioidfiles
Key: ATBfLhl+ReFHYcj3PVFaFETKN3JAvQJpSPyC3eItYbLYOnR5UgzXoESGwWdQFhuF2LODR757/dMJMVjV+l3Txg==
```

# Pasos para crear un file server
## 2. Del siguiente tutorial:

https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-use-table-storage-web-site/

Realizar los siguientes pasos e ir comiteando según corresponda:

Install modules and generate scaffolding
Create the application (No utilizar la parte del modelo de Task, para eso utilizar el método createBlockBlobFromStream de aquí https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/) 
Run the application locally

## 3. Hacer push y controlar que el repositorio sea accesible en http://crearfileserver.azurewebsites.net/

**Comment by AlexisNichel** [comment]
listo el servicio

**Comment by AlexisNichel** [comment]
integrado con ionic, lo probe 2 veces, faltaria mas pruebas e incluirlo en la guia de pruebas
