### ISSUE TITLE
Utilizar nombres del dominio

### ISSUE THREAD

**Issue by camposcristianeze** [AlexisNichel/bioid-mobile-base#9]
Evitar nombres como "datos" u "obj/objeto" . Son nombres que pueden representar todo tipo de cosas y no modelan el tipo de negocio. Ejemplo:

![image](https://cloud.githubusercontent.com/assets/1928706/13857547/1d002a90-ec59-11e5-8166-edc931b9c630.png)

En este caso, se está trayendo un user, o un employee. 

Hay más "datosObj" en los js. Revisar la aplicación en busca de estos nombres y corregirlos

**Comment by AlexisNichel** [comment]
ok
